/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings` (hash: 698ae9e5dce149fd6d1e42330f4db0f3)
interface __BaseEnv_CloudflareBindings {
	KARV_ANALYTICS: AnalyticsEngineDataset;
	AI_API_ENABLED: string;
	AI_GATEWAY_BASE_URL: string;
	ALLOWED_ORIGINS: string;
	KARV_DEFAULT_PROJECT: string;
	KARV_PROJECTS: string;
	KARV_PROJECT_POLICIES: string;
	OPENAI_MODEL: string;
	ANTHROPIC_MODEL: string;
	REPORT_DELIVERY_ENABLED: string;
	REPORTING_API_ENABLED: string;
	AI_RATE_LIMITER: RateLimit;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		KARV_ANALYTICS: AnalyticsEngineDataset;
		AI_API_ENABLED: string;
		AI_GATEWAY_BASE_URL: string;
		ALLOWED_ORIGINS: string;
		KARV_DEFAULT_PROJECT: string;
		KARV_PROJECTS: string;
		KARV_PROJECT_POLICIES: string;
		OPENAI_MODEL: string;
		ANTHROPIC_MODEL: string;
		REPORT_DELIVERY_ENABLED: string;
		REPORTING_API_ENABLED: string;
		AI_RATE_LIMITER: RateLimit;
	}
	interface ProductionEnv {
		KARV_ANALYTICS: AnalyticsEngineDataset;
		AI_API_ENABLED: string;
		AI_GATEWAY_BASE_URL: string;
		ALLOWED_ORIGINS: string;
		KARV_DEFAULT_PROJECT: string;
		KARV_PROJECTS: string;
		KARV_PROJECT_POLICIES: string;
		OPENAI_MODEL: string;
		ANTHROPIC_MODEL: string;
		REPORT_DELIVERY_ENABLED: string;
		REPORTING_API_ENABLED: string;
		AI_RATE_LIMITER: RateLimit;
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
